### ISSUE TITLE
Error getting user

### ISSUE THREAD

**Issue by blaired** [BojanBuhac/M365-Copilot-Audit-Report#2]
Hi there, great dashboard :-)

I've ran into this error when trying to run Audit-Get-Users.ps1.  Running PS ver 7.4.6

![image](https://github.com/user-attachments/assets/2839c864-e793-42ff-abd0-6314acc40b8b)

**Comment by BojanBuhac** [comment]
Hi @blaired 
Please check module version (update to latest version) and necessary permissions on EntraID. 

Are you by any chance Global Admin in your tenant?

**Comment by blaired** [comment]
All resolved now.  I was running on my Mac and moved my PC and it's all OK :-)
